[package]
name = "pushgp"
version = "0.1.0"
authors = ["johker <johannes.kern@zoho.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
